In [1]:
import numpy as np
from sklearn.datasets import load_iris

In [2]:
iris_dataset = load_iris()

In [4]:
iris_dataset.data.shape

(150, 4)

We already know that n_neighbors=9 is good.

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], test_size=0.40,
random_state=0)

# build the model
clf = KNeighborsClassifier(n_neighbors=9)
clf.fit(X_train, y_train)
# record training set accuracy
print(clf.score(X_train, y_train))
# record generalization accuracy
print(clf.score(X_test, y_test))
    

0.9888888888888889
0.9666666666666667


In [13]:
X_test[:10,:]

array([[5.8, 2.8, 5.1, 2.4],
       [6. , 2.2, 4. , 1. ],
       [5.5, 4.2, 1.4, 0.2],
       [7.3, 2.9, 6.3, 1.8],
       [5. , 3.4, 1.5, 0.2],
       [6.3, 3.3, 6. , 2.5],
       [5. , 3.5, 1.3, 0.3],
       [6.7, 3.1, 4.7, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [6.1, 2.8, 4. , 1.3]])

In [10]:
clf.predict([X_test[0]])

array([2])

In [32]:
y_test[:10]

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1])

Save model as pickle

In [17]:
import pickle

In [18]:
%%time
pickle_out = open("model.pickle","wb")
pickle.dump(clf, pickle_out)
pickle_out.close()

Wall time: 24.8 ms


Load pickle

In [19]:
pickle_in = open("model.pickle","rb")
model = pickle.load(pickle_in)

In [22]:
model.predict([[5.8, 2.8, 5.1, 2.4]])

array([2])

In [28]:
a = '5.8,2.8,5.1,2.4'
b = list(map(float,a.split(',')))
model.predict([b])[0]

2

In [30]:
str(b)

'[5.8, 2.8, 5.1, 2.4]'

In [31]:
iris_dataset.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')